#!/bin/sh

# Usage:
#
# git remaster [branch]
#
# Rebases the indicated branch (or the current branch) on top of the
# latest version of origin/master (updating master as well along the
# way).

if [ -z "$1" ]; then
    git checkout "$1" || exit $?
fi

git fetch origin || exit $?

master=$(git rev-parse master)
origin_master=$(git rev-parse origin/master)
if [ $master != $origin_master ]; then
    (git rebase origin/master master &&
     git checkout -) || exit $?
fi

git rebase master
