#!/bin/sh

# Usage:
#
# git land [branch]
#
# Rebases the indicated branch (or the current branch) on top of the
# latest version of origin/master (updating master as well along the
# way), as with git-remaster, and then merges the branch to master,
# and (assuming the previous was all successful), deletes the branch,
# leaving master ready to be pushed to origin with the new code.

git remaster "$@" &&
git checkout master &&
git merge @{-1} &&
git branch -d @{-1}
