#!/bin/sh

# Usage:
#
# git land [branch]
#
# Rebases the indicated branch (or the current branch) on top of the
# latest version of origin/master (updating master as well along the
# way), as with git-remaster, and then merges the branch to master,
# and (assuming the previous was all successful), deletes the branch,
# leaving master ready to be pushed to origin with the new code.

rev=$(git rev-parse --revs-only "$@")
args=$(git rev-parse --no-revs --sq "$@")

current_branch=$(git symbolic-ref HEAD)
current_branch=${current_branch##refs/heads/}

if [ -z "$rev" ]; then
    branch=$current_branch
else
    branch="$rev"
fi

if [ -z "$branch" ]; then
    echo "Could not determine branch" 1>&2
    exit 1
fi

master_name=$(git master-name)

git fetch --prune origin || exit $?

master=$(git rev-parse ${master_name})
origin_master=$(git rev-parse origin/${master_name})
if [ $master != $origin_master ]; then
    if [ $current_branch != ${master_name} ]; then
	git checkout ${master_name} || exit $?
    fi
    git pull || exit $?
    git checkout $branch || exit $?
else
    if [ $current_branch != $branch ]; then
	git checkout $branch || exit $?
    fi
fi

git rebase ${master_name} &&
git checkout ${master_name} &&
eval "git merge $args $branch" &&
git branch -D $branch
