#!/bin/sh

# Usage:
#
# git amend [git-commit options]
#
#   Merges the indicated (and/or already-staged) changes into HEAD.
#   Equivalent to "git commit --amend [options]", but just keeps the
#   existing commit message without prompting.
#
#
# git amend <commit> [git-commit options]
#
#   eg: git amend HEAD^^ -a
#
#   Merges the indicated (and/or already-staged) changes into the
#   given commit by first committing them rewriting history with git
#   rebase. If the rebase fails, you will be left inside the "git
#   rebase -i" operation. If the rebase fails, and there were unstaged
#   changes in the working tree that were not selected as part of the
#   amend operation, then those changes will have been stored in a
#   temporary commit at the top of the tree, and you can use
#   "git reset HEAD^" to uncommit them after fixing up the rebase.

rev=$(git rev-parse --revs-only "$@")
args=$(git rev-parse --no-revs --sq "$@")

if [ -z "$rev" ]; then
    eval "git commit --amend -C HEAD $args"
    exit $?
fi

eval "git commit --no-verify --quiet --fixup=$rev $args" || exit $?

if git commit -a -m 'unstaged changes during git-amend' > /dev/null; then
    unstaged_changes=1
fi

if ! GIT_EDITOR=true git rebase -i --autosquash "$rev"^; then
    exit $?
fi

if [ -n "$unstaged_changes" ]; then
    git reset -q HEAD^
fi
